import { expect, test } from '@playwright/test';
import { createLayer, defaultSettings, pianoPreset } from '../../src/domain/models';
import { makeBackup } from '../../src/domain/serialization';
import { factoryPresets } from '../../src/domain/factory';
test('four layers, mute during a held chord, preset save and restore with global master', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/'); await page.getByRole('button', { name: 'Увімкнути звук', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Звук готовий' })).toBeVisible();
  for (let i = 0; i < 3; i++) await page.locator('.empty-layer').first().click();
  const layers = page.locator('app-layer-editor'); await expect(layers).toHaveCount(4);
  await expect(layers.nth(1).getByLabel('Тембр', { exact: true })).toHaveValue('warm-pad');
  await expect(page.locator('.empty-layer')).toHaveCount(0);
  const key = page.getByRole('button', { name: 'C4', exact: true });
  await key.dispatchEvent('keydown', { code: 'Enter' }); await expect(page.getByTestId('voices')).toHaveText('4');
  await layers.nth(1).getByRole('button', { name: 'Mute', exact: true }).click();
  await expect(page.getByTestId('voices')).toHaveText('3');
  await page.getByLabel('Загальна транспозиція', { exact: true }).fill('12');
  await page.getByLabel('Загальна транспозиція', { exact: true }).blur();
  await key.dispatchEvent('keyup', { code: 'Enter' }); await expect(page.getByTestId('voices')).toHaveText('0');
  await page.locator('#master').fill('-18');
  await page.getByRole('button', { name: 'Керування пресетами' }).click();
  await page.getByLabel('Назва', { exact: true }).fill('Репетиція');
  await page.getByRole('button', { name: 'Закрити пресети' }).click();
  await page.getByRole('button', { name: 'Зберегти як', exact: true }).click();
  await page.getByLabel('Назва нового пресету', { exact: true }).fill('Репетиція');
  await page.getByRole('button', { name: 'Створити', exact: true }).click();
  await expect(page.locator('.statusbar')).toContainText('Пресет збережено');
  await page.reload(); await expect(page.getByLabel('Назва', { exact: true })).toHaveValue('Репетиція');
  await expect(layers).toHaveCount(4); await expect(page.locator('#master')).toHaveValue('-18');
  await expect(layers.nth(1).getByRole('button', { name: 'Mute', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByLabel('Загальна транспозиція', { exact: true })).toHaveValue('12');
  await expect(layers.nth(1).getByLabel('Тембр', { exact: true })).toHaveValue('warm-pad');
  await expect(page.getByLabel('Відкрити пресет', { exact: true }).locator('option:checked')).toHaveText('11 · Репетиція');
  await page.screenshot({ path: 'test-results/stage2-four-layers.png', fullPage: true });
  await page.getByLabel('Відкрити пресет', { exact: true }).selectOption('worship-piano');
  await expect(layers).toHaveCount(1); await expect(page.locator('#master')).toHaveValue('-18');
  await page.screenshot({ path: 'test-results/stage2-library.png', fullPage: true });
  expect(errors).toEqual([]);
});
test('import adds validated copies, rejects missing sounds and preserves globals and current draft', async ({ page }) => {
  const p = structuredClone(pianoPreset); p.name = 'Imported Pad'; p.layers = [createLayer('pad')];
  const backup = makeBackup([p], { ...defaultSettings, masterDb: 0 });
  await page.goto('/'); await expect(page.getByRole('button', { name: 'Зберегти як', exact: true })).toBeEnabled();
  await page.locator('#master').fill('-24');
  await page.getByRole('button', { name: 'Керування пресетами' }).click();
  const upload = async (data: unknown) => page.locator('input[type=file]').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(data)) });
  await upload(backup); await expect(page.getByRole('dialog').getByText('Імпортовано як нові копії;', { exact: false })).toBeVisible();
  await expect(page.getByLabel('Відкрити пресет', { exact: true }).locator('option')).toHaveCount(11);
  await expect(page.locator('#master')).toHaveValue('-24');
  await expect(page.getByLabel('Назва', { exact: true })).toHaveValue(factoryPresets[0]!.name);
  const broken = structuredClone(backup); broken.presets[0]!.layers[0]!.instrument.id = 'missing';
  await upload(broken); await expect(page.getByRole('dialog').getByRole('alert')).toContainText('відсутній або несумісний інструмент');
  await expect(page.getByLabel('Відкрити пресет', { exact: true }).locator('option')).toHaveCount(11);
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Експорт JSON' }).click();
  expect((await download).suggestedFilename()).toBe('live-keys-presets.json');
});
test('autosave restores unsaved edits and denied writes remain visible without disabling playback', async ({ page }) => {
  await page.goto('/'); await page.locator('.empty-layer').first().click();
  await expect(page.locator('.statusbar').getByText('Чернетку збережено локально', { exact: true })).toBeVisible();
  await page.reload(); await expect(page.locator('app-layer-editor')).toHaveCount(2);
  await expect(page.getByLabel('Є незбережені зміни', { exact: true })).toBeVisible();
  await page.evaluate(() => { IDBObjectStore.prototype.put = () => { throw new DOMException('Quota', 'QuotaExceededError'); }; });
  await page.locator('.empty-layer').first().click();
  await expect(page.getByRole('alert')).toContainText('Не вдалося прочитати або зберегти');
  await page.getByRole('button', { name: 'Увімкнути звук', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Звук готовий' })).toBeVisible();
  await page.getByRole('button', { name: 'Керування пресетами' }).click();
  await expect(page.getByRole('button', { name: 'Експорт JSON' })).toBeEnabled();
});
