export const uk = {
  title: 'Live Keys', subtitle: 'Шари для живої гри', stage: 'Бібліотека та ефекти · 0.3',
  start: 'Увімкнути звук', resume: 'Відновити звук', loading: 'Підготовка звуку…', ready: 'Звук готовий',
  audio: 'Аудіо', midi: 'MIDI-клавіатура', allowMidi: 'Дозволити MIDI', midiBusy: 'Очікування дозволу…',
  midiHelp: 'Дозвольте MIDI й виберіть один або кілька входів. MIDI передає ноти; звук виходить із комп’ютера.',
  noInputs: 'Входів немає. Під’єднайте клавіатуру через USB і перевірте живлення.',
  midiUnsupported: 'Web MIDI недоступний. Використайте настільний Chrome через HTTPS або localhost. Екранна клавіатура залишається доступною.',
  midiDenied: 'Доступ до MIDI не надано. Дозвольте його в налаштуваннях сайту та повторіть спробу.',
  midiError: 'Не вдалося підключити MIDI. Перевірте дозволи й повторіть спробу.',
  disconnected: 'Від’єднано MIDI-вхід. Його ноти зупинено. Після підключення виберіть вхід знову:',
  audioError: 'Не вдалося підготувати звук. Перевірте доступність локальних семплів і натисніть «Увімкнути звук» повторно.',
  audioUnsupported: 'Web Audio недоступний у цьому браузері.',
  instrument: 'Natural Grand', demo: '38 тембрів · 7 категорій',
  demoHelp: 'Роялі: записи Salamander, 3 рівні velocity; компактний demo-банк. Електропіано, педи й ліди: синтез. Тембри потребують прослуховування на вашому аудіовиході.',
  master: 'Загальна гучність', silence: 'Тиша', panic: 'Panic', panicDone: 'Усі ноти та sustain скинуто. Можна грати знову.',
  sustain: 'Sustain для екранних клавіш', pedal: 'Активних sustain-каналів',
  keys: 'Екранна клавіатура', keyHelp: 'Миша або кілька дотиків. Клавіші A W S E D F T G Y H U J K — від C4. Escape — Panic.',
  voices: 'Голоси', profile: 'Ліміт голосів', low: '32 · легкий', normal: '64 · звичайний',
  diagnostics: 'Діагностика', samples: 'Семпли', memory: 'Декодований PCM', rate: 'Частота',
  baseLatency: 'baseLatency', outputLatency: 'outputLatency', unavailable: 'недоступно',
  latencyHelp: 'Це часткові оцінки браузера. MIDI-to-audio затримка не виміряна — потрібне фізичне обладнання.',
  outputHelp: 'Вихід: системний аудіопристрій. Змініть його в налаштуваннях ОС. Для перевірки гри використовуйте дротове аудіо.',
  protection: 'Лімітер піків семплів без lookahead. Не true-peak; граничний рівень задається в ефектах.',
  pre: 'До лімітера', post: 'Після лімітера', clipping: 'Перевантаження',
  attribution: 'Семпли: Salamander Grand Piano — Alexander Holm · CC BY 3.0',
  hardware: 'MIDI, педаль, затримка й стабільність на обладнанні потребують ручної перевірки.',
  offline: 'Offline reload ще не реалізовано.',
  running: 'Працює', suspended: 'Призупинено — відновіть звук', closed: 'Закрито', notStarted: 'Ще не увімкнено',
  layers: 'Шари', addPiano: 'Додати рояль', addPad: 'Додати пед', sound: 'Тембр', removeLayer: 'Прибрати',
  enabled: 'Увімкнено', mute: 'Mute', solo: 'Solo', layerVolume: 'Гучність шару', pan: 'Панорама', transpose: 'Транспозиція',
  keyLow: 'Ноти від (MIDI)', keyHigh: 'Ноти до (MIDI)', velocityLow: 'Velocity від', velocityHigh: 'Velocity до',
  velocityCurve: 'Чутливість', linear: 'Лінійна', soft: 'М’яка', hard: 'Жорстка', fixed: 'Фіксована · 100',
  fineTune: 'Стрій (cents)', channel: 'MIDI-канал', omni: 'Усі канали', layerInput: 'Входи шару', allInputs: 'Усі вибрані / екранні',
  missingInput: 'Недоступний вхід:', layerSustain: 'Реагувати на sustain', layerDetails: 'Динаміка та MIDI',
  attack: 'Атака (s)', release: 'Затухання (s)', cutoff: 'Яскравість', globalTranspose: 'Загальна транспозиція',
  library: 'Пресети', presetName: 'Назва', save: 'Зберегти', saveCopy: 'Зберегти копію', delete: 'Видалити',
  confirmDelete: 'Видалити вибраний пресет?', cancel: 'Скасувати', openPreset: 'Відкрити пресет', factory: 'Заводський рояль · Demo',
  export: 'Експорт JSON', import: 'Імпорт JSON', dirty: 'Є незбережені зміни', saved: 'Пресет збережено',
  draftSaved: 'Чернетку збережено локально', draftSaving: 'Збереження чернетки…', draftRestored: 'Відновлено локальну чернетку.',
  storageError: 'Не вдалося прочитати або зберегти локальні дані. Грати можна; зробіть експорт JSON і повторіть збереження.',
  importError: 'Файл не імпортовано: перевірте формат, версію та діапазони. Поточні дані збережено.',
  missingSounds: 'Файл містить відсутній або несумісний інструмент чи банк. Дані не змінено.',
  fileTooLarge: 'Перевищено ліміт: файл до 1 MiB та 100 записів; бібліотека до 99 збережених пресетів.', imported: 'Імпортовано як нові копії; поточний звук і загальні налаштування збережено.',
  exported: 'Експортовано пресети, поточну чернетку й загальні налаштування. Семпли у файл не входять.',
  layersHelp: 'Діапазони включають обидві межі та можуть перекриватися. Зміна нот і транспозиції діє на нові натискання.',
  presetHelp: '«Зберегти» перезаписує ваш пресет; «Зберегти як» створює новий, зокрема із заводського. Імпорт додає копії; master, MIDI-входи й загальну транспозицію він не змінює.',
  switching: 'Підготовка звуку…', switchError: 'Новий звук не підготовлено. Поточний пресет продовжує працювати.',
  switchHelp: 'Зберігаються голоси двох попередніх пресетів; найстаріші плавно завершуються. Повні переходи з ефектами ще попереду.',
  unsavedSwitch: 'Є незбережені зміни. Збережіть їх або відкрийте інший пресет без збереження.', openWithoutSaving: 'Відкрити без збереження',
  settingsSaved: 'Загальні налаштування збережено', restoredInputs: 'Збережені MIDI-входи потрібно вибрати знову після дозволу.',
  copySuffix: 'копія',
  movement: 'Рух тембру', mono: 'Mono · остання нота', glide: 'Glide (s)', bendRange: 'Pitch bend (півтони)', expression: 'Expression · CC11',
  layerEffects: 'Ефекти шару', effects: 'Спільні ефекти та EQ', filterCutoff: 'Фільтр (Hz)', resonance: 'Резонанс (Q)',
  chorusRate: 'Chorus rate (Hz)', chorusDepth: 'Chorus depth (s)', chorusMix: 'Chorus mix', chorusBypass: 'Chorus bypass',
  reverbSend: 'Reverb send', delaySend: 'Delay send', reverbDecay: 'Reverb decay (s)', reverbBypass: 'Reverb bypass',
  delayTime: 'Delay time (s)', feedback: 'Delay feedback', delayBypass: 'Delay bypass', delaySync: 'Delay sync',
  bpm: 'Темп (BPM)', division: 'Тривалість delay', tap: 'Tap tempo', eqLow: 'EQ низ (dB)', eqMid: 'EQ середина (dB)', eqHigh: 'EQ верх (dB)',
  ceiling: 'Ліміт піків (dBFS)', reduction: 'Зменшення рівня', effectsHelp: 'Sync використовує темп і тривалість; вимкніть Sync для часу в секундах. Ефекти отримують звук через sends шарів. Зміна decay оновлює хвости.',
  banks: 'Банки звуків', bankReady: 'Готовий у пам’яті', bankMissing: 'Не завантажено', bankLoading: 'Завантаження…', bankError: 'Помилка завантаження',
  loadBank: 'Завантажити / повторити', bankHelp: 'Grand Piano — рояль. FluidR3 — педи, оркестр і хор. Legacy — сумісність зі старими роялями. Готовність у пам’яті не гарантує offline reload.',
  bankFailure: 'Банк не завантажено. Перевірте доступ до файлів і повторіть спробу.', effectsMemory: 'Пам’ять реверберації',
  outputMono: 'Mono-вихід · середнє L/R',
};
